[project]
name = "upstageailab-cv-classification-cv-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "albumentations==1.3.1",
    "ipykernel==6.27.1",
    "ipython==8.15.0",
    "ipywidgets==8.1.1",
    "jupyter==1.0.0",
    "matplotlib-inline==0.1.6",
    "numpy==1.26.0",
    "pandas==2.1.4",
    "pillow==9.4.0",
    "timm==0.9.12",
]
