# @package _global_
defaults:
  - config

# EfficientNet v2 Small (Pure PyTorch)
model:
  name: "efficientnetv2_s"
  num_classes: 17
  pretrained: false  # 사전훈련 가중치 없음

training:
  lr: 1e-3
  epochs: 1
  batch_size: 32
  seed: 42

data:
  img_size: 224
  num_workers: 0

device: mps

output:
  filename: "pred_efnv2s_pure.csv" 