# @package _global_
defaults:
  - config

# EfficientNet v2 RandomWiring Medium
model:
  name: "efficientnetv2_rw_m"
  num_classes: 17
  pretrained: true

train:
  lr: 1e-3
  epochs: 1
  batch_size: 24
  seed: 42

data:
  img_size: 224
  num_workers: 0

device: mps

output:
  filename: "pred_efnv2rw_m.csv" 