# @package _global_
defaults:
  - config
  - _self_

# Fast test configuration
model:
  name: "resnet18"
  num_classes: 17
  pretrained: true

training:
  lr: 1e-3
  epochs: 1
  batch_size: 64
  seed: 42
  
  # Label Smoothing configuration
  label_smoothing:
    enabled: true
    smoothing: 0.1  # 0.0 ~ 1.0, 일반적으로 0.1
  
  # Mixed Precision Training configuration
  mixed_precision:
    enabled: true

  # Data augmentation configuration
  augmentation:
    method: "mix"            # "none", "albumentations", "augraphy", "mix"
    intensity: 0.5             # 0.0 ~ 1.0 augmentation strength
    train_count: 1             # number of augmented copies per image
    valid_count: 1             # augmentation copies for validation dataset
    valid_tta: 1               # TTA count during validation
    test_tta: 1                # TTA count during inference
    # Available Albumentations ops:
    # horizontal_flip, vertical_flip, random_rotate90, rotate, transpose,
    # shift_scale_rotate, optical_distortion, grid_distortion, elastic_transform,
    # perspective, random_brightness_contrast, color_jitter, hsv, random_gamma,
    # clahe, to_gray, channel_shuffle, invert, gauss_noise, blur, motion_blur,
    # median_blur, downscale, jpeg, sharpen, emboss, piecewise_affine,
    # random_resized_crop, center_crop, random_crop, pad_if_needed,
    # coarse_dropout, channel_dropout, fancy_pca, equalize, posterize,
    # solarize, iso_noise, multiplicative_noise, random_grid_shuffle,
    # random_shadow, random_sunflare, random_fog, random_rain, random_snow,
    # zoom_blur, grid_dropout, gaussian_blur, glass_blur, pixel_dropout
    # Available Augraphy ops:
    # ink_bleed, ink_mottling, ink_shifter, low_ink_random_lines,
    # low_ink_periodic_lines, color_paper, brightness_texturize,
    # dirty_rollers, dirty_drum, stains, page_border, geometric,
    # lighting_gradient, brightness, color_shift, noise_texturize,
    # subtle_noise, shadow_cast, lines_degradation, bleed_through,
    # markup, scribbles, jpeg
    train_ops: [all]           # list of op names (Albumentations/Augraphy) or [all]
    valid_ops: [all]              # Albumentations/Augraphy ops for validation dataset
    valid_tta_ops: [rotate]    # ops applied for validation TTA
    test_tta_ops: [rotate]     # ops applied for inference TTA
    
data:
  img_size: 64
  num_workers: 0 


# Device configuration
device: "cuda"  # "cuda" or "cpu" or "mps"