# @package _global_
defaults:
  - config

# EfficientNet v2 Large (Pure PyTorch)
model:
  name: "efficientnetv2_l"
  num_classes: 17
  pretrained: false  # 사전훈련 가중치 없음

train:
  lr: 1e-3
  epochs: 1
  batch_size: 16
  seed: 42

data:
  img_size: 224
  num_workers: 0

device: mps

output:
  filename: "pred_efnv2l_pure.csv" 