# Holdout validation configuration
defaults:
  - config

# Override validation strategy
validation:
  strategy: "holdout"
  
  # Holdout configuration
  holdout:
    train_ratio: 0.8
    stratify: true
    
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
    monitor: "val_loss"
    mode: "min"

# Training configuration
train:
  lr: 1e-3
  epochs: 30
  batch_size: 32
  seed: 42

# W&B configuration
wandb:
  enabled: false
  run_name: "holdout_validation"
  tags: ["holdout", "validation"]
  notes: "Holdout validation with early stopping" 