# 새로운 기능 테스트를 위한 설정 파일
# Label Smoothing과 Mixed Precision Training을 활성화

# Hydra configuration for testing new features
defaults:
  - _self_

# Data configuration
data:
  data_path: "../../input/data"
  img_size: 32
  num_workers: 0

# Model configuration
model:
  name: "resnet18"  # 더 작은 모델로 테스트
  num_classes: 17
  pretrained: false  # 빠른 테스트를 위해 false

# Training configuration
train:
  lr: 1e-3
  epochs: 2  # 짧은 테스트
  batch_size: 16
  seed: 42
  
  # Label Smoothing configuration (새로운 기능)
  label_smoothing:
    enabled: true
    smoothing: 0.1
  
  # Mixed Precision Training configuration (새로운 기능)
  mixed_precision:
    enabled: true
    
  # Learning rate scheduler configuration
  scheduler:
    enabled: true
    name: "cosine"
    cosine:
      T_max: 2  # epochs와 맞춤
      eta_min: 1e-6
      last_epoch: -1

# Validation configuration
validation:
  strategy: "holdout"
  holdout:
    train_ratio: 0.8
    stratify: true
  early_stopping:
    enabled: false  # 짧은 테스트를 위해 비활성화

# Device configuration
device: "cuda"  # Mixed Precision 테스트를 위해 CUDA 사용 (가능한 경우)

# Output configuration
output:
  dir: "results"
  filename: "pred_test_features.csv"

# Model saving configuration
model_save:
  dir: "models"
  wandb_artifact: false  # 테스트를 위해 비활성화

# W&B configuration
wandb:
  enabled: false  # 테스트를 위해 비활성화
  project: null
  entity: null
  run_name: "test_new_features"
  tags: ["label_smoothing", "mixed_precision", "test"]
  notes: "Testing Label Smoothing and Mixed Precision Training" 