# @package _global_
defaults:
  - config

# Test wandb artifact
model:
  name: "tf_efficientnetv2_s"
  num_classes: 17
  pretrained: true

train:
  lr: 1e-3
  epochs: 1
  batch_size: 32
  seed: 42

data:
  img_size: 224
  num_workers: 0

device: mps

model_save:
  enabled: true
  dir: "models"
  save_best: true
  save_last: false
  wandb_artifact: true  # wandb 아티팩트 등록 활성화

wandb:
  enabled: true  # wandb 활성화
  project: "cv_classification_test"
  entity: null
  run_name: "model_save_test"
  tags: ["test", "model_save"]
  notes: "모델 저장 및 wandb 아티팩트 등록 테스트"

output:
  filename: "pred_wandb_test.csv" 