# Hydra configuration for exp3 experiment
defaults:
  - _self_

# Data configuration
data:
  data_path: "../../input/data"
  img_size: 32
  num_workers: 0

# Model configuration
model:
  name: "resnet34"
  num_classes: 17
  pretrained: true

# Training configuration
training:
  lr: 1e-3
  epochs: 1
  batch_size: 32
  seed: 42

# Validation configuration
validation:
  # Validation strategy: "holdout", "kfold", or "none"
  strategy: "holdout"  # "holdout", "kfold", "none"
  
  # Holdout configuration
  holdout:
    train_ratio: 0.8
    stratify: true
    
  # K-fold configuration
  kfold:
    n_splits: 5
    stratify: true
    
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
    monitor: "val_loss"  # "val_loss", "val_acc", "val_f1"
    mode: "min"  # "min" for loss, "max" for accuracy/f1

# Device configuration
device: "cuda"  # "cuda" or "cpu"

# Output configuration
output:
  dir: "results"
  filename: "pred.csv"

# W&B configuration
wandb:
  enabled: false
  project: null
  entity: null  # will be loaded from .env file
  run_name: "jhryu_v5_valid_test"  # auto-generated if null
  tags: []
  notes: ""
