# K-Fold cross validation configuration
defaults:
  - config

# Override validation strategy
validation:
  strategy: "kfold"
  
  # K-fold configuration
  kfold:
    n_splits: 5
    stratify: true
    
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
    monitor: "val_loss"
    mode: "min"

# Training configuration
training:
  lr: 1e-3
  epochs: 30
  batch_size: 32
  seed: 42

# W&B configuration
wandb:
  enabled: false
  run_name: "kfold_validation"
  tags: ["kfold", "cross_validation", "ensemble"]
  notes: "5-fold cross validation with early stopping and ensemble" 