# Quick test configuration with holdout
defaults:
  - config

# Override validation strategy
validation:
  strategy: "holdout"
  
  # Holdout configuration
  holdout:
    train_ratio: 0.8
    stratify: true
    
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 3
    min_delta: 0.001
    monitor: "val_loss"
    mode: "min"

# Training configuration
training:
  lr: 1e-3
  epochs: 5  # 빠른 테스트용으로 적은 epoch
  batch_size: 32
  seed: 42

# W&B configuration
wandb:
  enabled: false  # 빠른 테스트용으로 비활성화
  run_name: "test_holdout"
  tags: ["test", "holdout"]
  notes: "Quick test with holdout validation" 