# Quick test configuration with K-Fold
defaults:
  - config

# Override validation strategy
validation:
  strategy: "kfold"
  
  # K-fold configuration
  kfold:
    n_splits: 3  # 빠른 테스트용으로 적은 fold
    stratify: true
    
  # Early stopping configuration
  early_stopping:
    enabled: true
    patience: 2
    min_delta: 0.001
    monitor: "val_loss"
    mode: "min"

# Training configuration
train:
  lr: 1e-3
  epochs: 3  # 빠른 테스트용으로 적은 epoch
  batch_size: 32
  seed: 42

# W&B configuration
wandb:
  enabled: false  # 빠른 테스트용으로 비활성화
  run_name: "test_kfold"
  tags: ["test", "kfold"]
  notes: "Quick test with K-Fold validation" 